apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql2017-vc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile
  volumeName: sql2017-pv
