apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sqlserver2017
  labels:
    app: sqlserver2017-deployment
spec:
  selector:
    matchLabels:
      app: sqlserver2017-deployment
  template:
    metadata:
      labels:
        app: sqlserver2017-deployment
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "P@ssw0rd1234"
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: sql2017-vc

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: sqlserver2017-svc
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: amrydemodb
spec:
  selector:
    app: sqlserver2017-deployment
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
  # type: ClusterIP
