apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql2017-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: sqlstorage-secret
    shareName: sqlserver
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
